apiVersion: v1
kind: Pod
metadata:
  name: containers-wo-volume
spec:
  containers:
	- name: container1
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
  - name: container2
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"