apiVersion: v1
kind: Pod
metadata:
  name: downwardapi-example
  labels:
    app: my-app
spec:
  containers:
  - name: app-container
    image: busybox
    command: 
      - "/bin/sh"
      - "-c"
      - "cat /podinfo/labels" 
      - "sleep 3600"
    volumeMounts:
    - mountPath: /podinfo
      name: pod-metadata
  volumes:
  - name: pod-metadata
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels