apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  username: admin
  password: s3cr3t

---

apiVersion: v1
kind: Pod
metadata:
  name: secret-example
spec:
  containers:
  - name: app-container
    image: busybox
    command: 
      - "/bin/sh"
      - "-c"
      - "cat /secrets/username"
      - "cat /secrets/password"
      - "sleep 3600"
    volumeMounts:
    - mountPath: /secrets
      name: secret-volume
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret