apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: kube-tut
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP