apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod2
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: color
        valueFrom: 
          configMapKeyRef:
            name: app-config2
            key: app.color