apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-pod
  name: nginx-service
  namespace: kube-tut
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-pod
  type: ClusterIP