apiVersion: v1
kind: Service
metadata:
  labels:
    demo: "true"
    env: dev
  name: nginx-service
  namespace: kube-tut
spec:
  ports:
  - nodePort: 32125
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    demo: "true"
    env: dev
  type: NodePort